DROP  TRIGGER TG_KEY_CUSTOMER;
DROP  TRIGGER TG_KEY_PRODUCT;
DROP  TRIGGER TG_KEY_ORDERT;
DROP  TRIGGER TG_KEY_ORDER_DETAIL;
DROP  TRIGGER TG_KEY_PERSONA;

DROP SEQUENCE SEQ_CUSTOMER_ID;
DROP SEQUENCE SEQ_PRODUCT_ID;
DROP SEQUENCE SEQ_ORDERT_ID;
DROP SEQUENCE SEQ_ORDER_DETAIL_ID;
DROP SEQUENCE SEQ_PERSONA_ID;

DROP TABLE ORDER_DETAIL;
DROP TABLE ORDERT;
DROP TABLE CUSTOMER;
DROP TABLE PRODUCT;
DROP TABLE PERSONA;

--------------------------------------------------------------------------------
-------------------------------- TABLES ----------------------------------------

CREATE TABLE CUSTOMER(
  ID NUMBER NOT NULL,
  FIRST_NAME VARCHAR2(50) NOT NULL,
  LAST_NAME VARCHAR2(50) NOT NULL,
  TAX_IDENTIFICATION_NUMBER VARCHAR2(50),
  CUSTOMER_CODE VARCHAR2(50),
  BIRTH_DATE DATE,
  PRIMARY KEY(ID),
  CONSTRAINT UQ_CUSTOMER_TAX_IDENTIFICATION_NUMBER UNIQUE(TAX_IDENTIFICATION_NUMBER),
  CONSTRAINT UQ_CUSTOMER_CUSTOMER_CODE UNIQUE(CUSTOMER_CODE)
);

CREATE TABLE PRODUCT(
  ID NUMBER NOT NULL,
  DESCRIPTION VARCHAR2(100) NOT NULL,
  PRODUCT_CODE VARCHAR2(50) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE ORDERT(
  ID NUMBER NOT NULL,
  DOCUMENT_NUMBER NUMBER,
  ORDERR_DATE DATE NOT NULL,
  CUSTOMER_ID NUMBER NOT NULL,
  PRIMARY KEY(ID),
  CONSTRAINT UQ_ORDERT_DOCUMENT_NUMBER UNIQUE(DOCUMENT_NUMBER),
  CONSTRAINT FK_ORDERT_CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE ORDER_DETAIL(
  ID NUMBER NOT NULL,
  ORDERT_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  QUANTITY NUMBER(18,6) NOT NULL,
  PRIMARY KEY(ID),
  CONSTRAINT FK_ORDER_DETAIL_ORDERT_ID FOREIGN KEY(ORDERT_ID) REFERENCES ORDERT(ID),
  CONSTRAINT FK_ORDER_DETAIL_PRODUCT_ID FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID)  
);

CREATE TABLE PERSONA(
  ID NUMBER NOT NULL,
  FIRST_NAME VARCHAR2(50) NOT NULL,
  LAST_NAME VARCHAR2(50) NOT NULL,
  PHONE VARCHAR2(50),
  PRIMARY KEY(ID)
);

--------------------------------------------------------------------------------
-------------------------------- SEQUENCE --------------------------------------

CREATE SEQUENCE SEQ_CUSTOMER_ID MINVALUE 1 MAXVALUE 9999 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT_ID MINVALUE 1 MAXVALUE 9999 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDERT_ID MINVALUE 1 MAXVALUE 9999 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDER_DETAIL_ID MINVALUE 1 MAXVALUE 9999 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PERSONA_ID MINVALUE 1 MAXVALUE 9999 START WITH 1 INCREMENT BY 1;

--------------------------------------------------------------------------------
-------------------------------- TRIGGERS --------------------------------------
CREATE TRIGGER TG_KEY_CUSTOMER BEFORE INSERT ON CUSTOMER FOR EACH ROW
BEGIN 
    SELECT SEQ_CUSTOMER_ID.NEXTVAL INTO : NEW.ID FROM DUAL;
END;

CREATE TRIGGER TG_KEY_PRODUCT BEFORE INSERT ON PRODUCT FOR EACH ROW
BEGIN 
    SELECT SEQ_PRODUCT_ID.NEXTVAL INTO : NEW.ID FROM DUAL;
END;

CREATE TRIGGER TG_KEY_ORDERT BEFORE INSERT ON ORDERT FOR EACH ROW
BEGIN 
    SELECT SEQ_ORDERT_ID.NEXTVAL INTO : NEW.ID FROM DUAL;
END;

CREATE TRIGGER TG_KEY_ORDER_DETAIL BEFORE INSERT ON ORDER_DETAIL FOR EACH ROW
BEGIN 
    SELECT SEQ_ORDER_DETAIL_ID.NEXTVAL INTO : NEW.ID FROM DUAL;
END;

CREATE TRIGGER TG_KEY_PERSONA BEFORE INSERT ON PERSONA FOR EACH ROW
BEGIN 
    SELECT SEQ_PERSONA_ID.NEXTVAL INTO : NEW.ID FROM DUAL;
END;

--------------------------------------------------------------------------------
-------------------------------- DATA ------------------------------------------

INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, TAX_IDENTIFICATION_NUMBER, CUSTOMER_CODE, BIRTH_DATE) 
    VALUES(1, 'Walter', 'Bates', '1234', 'C567', TO_DATE('1999-10-18','YYYY-MM-DD'));
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, TAX_IDENTIFICATION_NUMBER, CUSTOMER_CODE, BIRTH_DATE) 
    VALUES(2, 'April', 'Sanchez', '5678', 'C344', TO_DATE('1995-10-10','YYYY-MM-DD'));
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME, TAX_IDENTIFICATION_NUMBER, CUSTOMER_CODE,birth_date) 
    VALUES(3, 'Tomas', 'Harrison', '1909', 'C128',TO_DATE('1995-12-12','YYYY-MM-DD'));
INSERT INTO PRODUCT (ID, DESCRIPTION, PRODUCT_CODE) VALUES(1, 'Description Product A', 'P123');
INSERT INTO PRODUCT (ID, DESCRIPTION, PRODUCT_CODE) VALUES(2, 'Description Product B', 'P456');
INSERT INTO PRODUCT (ID, DESCRIPTION, PRODUCT_CODE) VALUES(3, 'Description Product C', 'P798');
INSERT INTO PRODUCT (ID, DESCRIPTION, PRODUCT_CODE) VALUES(4, 'Description Product D', 'P223');

/*
    SELECT * FROM DUAL;
    select * from all_sequences;
    SELECT PERSONA_ID_SEQ.nextval FROM DUAL;
    SELECT PERSONA_ID_SEQ.currval FROM DUAL;
*/
